sapphiredev/framework

src/index.ts, src/lib/SapphireClient.ts, src/lib/utils/logger/ILogger.ts, src/lib/utils/logger/Logger.ts
=> feat(core): added logger

README.md
This PR makes the README.md a bit pretty and better.
=> chore: make the readme better

.vscode/settings.json, src/lib/structures/Command.ts, src/lib/utils/Args.ts, src/lib/utils/strategies/FlagUnorderedStrategy.ts, tests/Flags.test.ts
=> feat(flags): Add flag parsing

package.json, yarn.lock
=> chore: fix eslint dependencies

README.md
since the widget is disabled I've chosen a custom badge, does it look good or should we use the "x online" one
=> readme: add support server

src/lib/utils/strategies/FlagUnorderedStrategy.ts
Following the examples in https://sapphire-project.github.io/framework/classes/args.html#getflags and https://sapphire-project.github.io/framework/classes/args.html#getoptions
=> fix: small docs inconsistency

src/arguments/CoreCategoryChannel.ts, src/lib/parsers/Args.ts
=> feat(arguments): add CoreCategoryChannel

src/errorEvents/CoreCommandError.ts, src/errorEvents/CoreEventError.ts, src/lib/SapphireClient.ts
=> feat: add optional default error events

package.json, src/events/command-handler/CorePrefixedMessage.ts, src/index.ts, src/lib/SapphireClient.ts, src/lib/parsers/Args.ts, src/lib/structures/ExtendedArgument.ts, src/lib/structures/StoreRegistry.ts, src/lib/utils/preconditions/PreconditionContainerSingle.ts, yarn.lock
This allows easy overriding of stores in plugins/user-code.
=> feat(client): change stores from a Set to a Map

src/lib/parsers/Args.ts
=> feat(args): add `name` to context of `Args.unavailableArgument`

package.json, src/arguments/CoreChannel.ts, src/arguments/CoreMessage.ts, src/arguments/CoreUser.ts, src/errorEvents/CoreCommandError.ts, src/errorEvents/CoreEventError.ts, src/events/CoreReady.ts, src/events/command-handler/CoreMessage.ts, src/events/command-handler/CoreMessageParser.ts, src/events/command-handler/CorePreCommandRun.ts, src/events/command-handler/CorePrefixedMessage.ts, src/index.ts, src/lib/SapphireClient.ts, src/lib/parsers/Args.ts, src/lib/structures/Event.ts, src/lib/structures/ExtendedArgument.ts, src/lib/utils/preconditions/PreconditionContainerSingle.ts, yarn.lock
- **BREAKING CHANGE**: Updated `@sapphire/pieces` to 2.0.0
=> fix: update `@sapphire/pieces` to v2.0.0

src/preconditions/NewsOnly.ts, src/preconditions/TextOnly.ts
The condition that a channel be a text channel and news channel was wrong.
=> fix(preconditions): fixed TextOnly and NewsOnly

src/lib/structures/Listener.ts
- :warning: **BREAKING CHANGE**: Listeners will now be automatically unloaded if no emitter is found
=> fix(listener): add and remove maximum listeners

src/lib/resolvers/channel.ts
=> feat(resolver): make resolveChannel parse mentions

src/lib/parsers/Result.ts
I thought this might be a nice chance to create my first Sapphire PR
Please go easy on me :')
=> feat: add `Result#from` and `Result#fromAsync`

src/arguments/CoreEnum.ts, src/lib/errors/Identifiers.ts, src/lib/parsers/Args.ts, src/lib/resolvers/enum.ts, src/lib/resolvers/index.ts
=> feat(arguments): enum argument

src/listeners/command-handler/CoreMessageParser.ts
| ⚠️ **Important:** This PR targets the `stable` branch which was created using the [`v2.3.0`](https://github.com/sapphiredev/framework/releases/tag/v2.3.0) tag as a base. After merging a new release, v2.4.0, will be made from that branch. |
| --- |
Furthermore, #372 will also be backported to the `stable` branch before v.2.4.0, ergo that this is tagged `SEM: Minor`
=> fix(message-parser): do not run commands when the bot has been timed out

src/lib/structures/Command.ts
=> fix(command): use CacheType generic consistently

src/lib/utils/application-commands/ApplicationCommandRegistry.ts, src/lib/utils/application-commands/normalizeInputs.ts
I really hate to do this but typedoc is shitting itself with these
2 lines and this is the only way around it until the rewrite is done
=> docs: ts ignore 2 lines for website

src/lib/parsers/Args.ts, src/lib/structures/Argument.ts
=> refactor: better Args Result types

src/lib/parsers/Args.ts
Some docs were using Result v1 code
=> docs: fix Result usage

package.json, src/arguments/CoreHyperlink.ts, src/index.ts, src/lib/parsers/Args.ts, src/lib/resolvers/hyperlink.ts, src/lib/structures/Argument.ts, src/lib/structures/Listener.ts, src/preconditions/ClientPermissions.ts, src/preconditions/Cooldown.ts, src/preconditions/DMOnly.ts, src/preconditions/Enabled.ts, src/preconditions/GuildNewsOnly.ts, src/preconditions/GuildNewsThreadOnly.ts, src/preconditions/GuildOnly.ts, src/preconditions/GuildPrivateThreadOnly.ts, src/preconditions/GuildPublicThreadOnly.ts, src/preconditions/GuildTextOnly.ts, src/preconditions/GuildThreadOnly.ts, src/preconditions/GuildVoiceOnly.ts, src/preconditions/NSFW.ts, src/preconditions/UserPermissions.ts, tests/resolvers/hyperlink.test.ts
=> refactor: cleanup types and ensure proper imports in dist

src/lib/utils/application-commands/ApplicationCommandRegistry.ts, src/lib/utils/application-commands/computeDifferences.ts, tests/application-commands/computeDifferences.test.ts
=> fix(computeDifferences): do not compute `dm_permissions` for guild-only commands

src/lib/structures/Command.ts, src/lib/structures/CommandStore.ts, src/lib/utils/application-commands/ApplicationCommandRegistries.ts, src/lib/utils/application-commands/ApplicationCommandRegistry.ts, src/lib/utils/application-commands/getNeededParameters.ts
Closes #522 
This should also solve the massive performance issues some members have had with the registry 👀
=> fix: only fetch guild ids for commands that require them

package.json
y'alls better not merge this till october
=> fix: fixed package description to remove mention of nonexistent /lib package

.eslintrc, package.json, src/lib/structures/InteractionHandlerStore.ts, yarn.lock
Also added an ESLint rule to make anything else show up. 
I'll port it to @sapphire/eslint-config in due time, I still want to update that config much more to better match all the work Crawl put into his.
=> fix: fixed deprecated djs code select menu

src/arguments/CoreGuild.ts, src/lib/errors/Identifiers.ts, src/lib/resolvers/guild.ts, src/lib/resolvers/index.ts
For some administration commands we need a guild argument, this pull request adds this.
=> feat(Args): add guild argument

src/lib/errors/Identifiers.ts, src/preconditions/GuildNewsOnly.ts, src/preconditions/GuildNewsThreadOnly.ts, src/preconditions/GuildPrivateThreadOnly.ts, src/preconditions/GuildPublicThreadOnly.ts, src/preconditions/GuildTextOnly.ts
- fix(identifiers): fix wrong string for Identifiers.ArgumentGuildNewsThreadChannelError
- fix(preconditions): resolve deprecated discordjs code
=> Fix 2 bugs before release

src/index.ts, src/lib/utils/application-commands/ApplicationCommandRegistries.ts, src/lib/utils/application-commands/ApplicationCommandRegistry.ts
This has been requested many times, so lets add it
=> feat: add global config for setting the guild ids to register commands to

src/preconditions/Cooldown.ts
=> refactor(cooldown): use id properties for channelId and guildId

src/preconditions/Cooldown.ts
Requested in #framework-development and also referencing https://github.com/sapphiredev/plugins/pull/504
=> refactor(cooldown): improve error message

src/lib/SapphireClient.ts
> **Warning**
> Before we can merge the 500 errors need to be resolved for the link https://discord.js.org/docs/packages/discord.js/main/ClientOptions:Interface
=> docs: fix link to discord.js

package.json
Similar to sapphiredev/plugins#537
=> fix: fixed commonjs typings export mapping

src/lib/utils/application-commands/ApplicationCommandRegistry.ts
Relates to [this discord thread](https://discord.com/channels/737141877803057244/1217868789073318007)
=> fix: resolved issue with registerOptions not picking up default options correctly

package.json, src/lib/resolvers/emoji.ts, yarn.lock
Depends on https://github.com/sapphiredev/utilities/pull/794
=> fix: use a custom instance of TwemojiRegex for validators and reset lastIndex
