src/lib/structures/Command.ts, src/lib/structures/CommandStore.ts
The classes have diverged a lot and barely anything is the same nowadays.
Anything that is left is pretty much public domain at this point.
=> chore(legal): remove copyright notices to Dirigeants

src/index.ts, src/lib/SapphireClient.ts, src/lib/extensions/SapphireMessage.ts, src/lib/utils/i18n/IInternationalization.ts, src/lib/utils/i18n/Internationalization.ts
=> feat(core): add base i18n handlers

src/events/command-handler/CoreMessageParser.ts
- allowing users to support prefixless commands by returning `''` in DMs.
=> fix: remove bug breaking prefixless commands

src/arguments/CoreMember.ts, src/arguments/CoreRole.ts, src/arguments/CoreUser.ts
I noticed that the user, role, and member arguments only resolve by IDs. As such, I decided to go ahead and, following consultation of other developers, implement the following:
- ID, mention and query parsing for members
- ID, mention and query parsing for roles
- ID and mention parsing for users (query is both infeasible and, as far as I'm concerned, not possible)
=> feat: implement additional parsing methods for core arguments

src/lib/errors/ArgumentError.ts, src/lib/errors/PreconditionError.ts, src/lib/errors/UserError.ts
This makes it possible to check what type of error it is by using `error.name`, so just a QoL option for developers.
=> refactor(errors): assign names to error classes

src/events/command-handler/CorePreCommandRun.ts
=> fix(events): Return early in CorePreCommandRun if the command is not enabled

src/arguments/CoreMember.ts, src/arguments/CoreRole.ts, src/arguments/CoreUser.ts
Two methods to retrieve an entity by either ID or mention is unnecessary if you just make the raw mention format itself an optional non-capturing group. Also removes the unnecessary `await` on `Collection#find` in the role argument's `resolveByQuery` method and adds catch handlers for Promises for a little extra reassurance.
=> feat(arguments): Improve ID/mention checking of members, roles, and users

src/index.ts, src/lib/structures/Argument.ts, src/lib/structures/ExtendedArgument.ts
The `ExtendedArgument` class allows a developer to expand upon the functionality of an existing argument in order to return, say, an argument of a more narrow type (e.g. `Channel` --> `TextChannel`) or to "subclass" an argument with restrictions (e.g. extending the `CoreString` argument to accept Discord snowflakes and then returning a `DeconstructedSnowflake` from `@sapphire/snowflake`). This should come with the benefits of cleaning up the existing core channel arguments and making the arguments system even more powerful and flexible than it already is. :)
=> feat(arguments): Add extended argument functionality

src/arguments/CoreGuildChannel.ts, src/arguments/CoreNewsChannel.ts, src/arguments/CoreTextChannel.ts, src/arguments/CoreVoiceChannel.ts, src/lib/utils/Args.ts
This introduces `GuildChannel` as a base argument for all guild-related channels, allowing for users to optionally mention channels rather than only being able to input the channel ID. This feature is why `guildChannel` does not extend `channel`; `GuildChannel` has more information-related properties like `name` that `Channel` doesn't have, allowing for searching for channels in the guild by name (similar to the role argument). From there, it makes more sense that `newsChannel`, `textChannel`, and `voiceChannel` inherit from `guildChannel`, since these all subclass `GuildChannel` anyways.
=> refactor(arguments): Add GuildChannel argument and use extended arguments for guild channels

src/lib/utils/Args.ts
Introduces `Args#peekWith` and `Args#peek` (alongside their `Result` variants), allowing arguments to be peeked without advancing the parser's state. `Args#peekWith` accepts a callback that returns the value from either `pickResult`, `repeatResult`, or `restResult`, saving the state before running the callback and restoring it afterwards; `Args#peek` is a convenience method for peeking a single argument.
=> feat(args): allow peeking arguments

src/lib/SapphireClient.ts
`Client#registerStore` exists, why shouldn't `Client#deregisterStore` to provide a typesafe chainable way to deregister as well as register?
=> feat: add client#deregisterStore

src/events/command-handler/CoreCommandAccepted.ts, src/lib/parsers/Args.ts, src/lib/structures/Argument.ts, src/lib/structures/Command.ts
This can be used to easily get access to the context for the command being ran.
In particular this is useful for retrieving the prefix that was being used, for example
to return context aware errors.
=> feat(args): add Args#commandContext

src/lib/structures/Precondition.ts
Since identifiers default to the Precondition's name, you don't need any options if you have no context. Now, the only way to do that is `this.error({})` which feels clunky.
=> fix(preconditions): make options optional

src/events/command-handler/CoreMessage.ts, src/events/command-handler/CoreMessageParser.ts, src/lib/types/Events.ts
This patch is useful for bots that want to customise the filters for message handling and those that want message editing without duplicating code from the framework.
=> feat(events): create Events.PreMessageParsed

guides/getting-started/CreatingCommands.mdx, guides/getting-started/CreatingEvents.mdx, guides/getting-started/GettingStarted.mdx
Hi, I've added the basics of a guide for Sapphire:
- Added content to GettingStarted.mdx to also talk about the file structure
- Added a CreatingCommands.mdx
- Added a CreatingEvents.mdx
**Few notes:**
I did not added that many files because as it is the very beginning, I didn't want to do too much until I had your opinions on it.
For other pages, you could talk about using arguments in commands (although even I am not sure about how to use them properly), or how to create arguments, either with `Args.make` or by extending the `Argument` Piece.
I've used JavaScript for the guide because the first page was using js, even though imho typescript would be better because sapphire seems to be made for ts.
English's not my native tongue so don't hesitate to correct my mistakes.
I've chosen to …
=> docs(guide): add basic guide

src/lib/errors/Identifiers.ts, src/lib/structures/Command.ts, src/lib/structures/ExtendedArgument.ts, src/lib/structures/StoreRegistry.ts, src/lib/utils/preconditions/PreconditionContainerArray.ts, src/preconditions/NewsOnly.ts, src/preconditions/TextOnly.ts
- feat(command): added auto-preconditions
- feat(command): added `CommandOptions.nsfw`
- feat(command): added `CommandOptions.cooldownBucket`
- feat(command): added `CommandOptions.cooldownDuration`
- feat(command): added `CommandOptions.runIn`
- feat(identifiers): added `Identifiers.PreconditionNewsOnly`
- feat(identifiers): added `Identifiers.PreconditionTextOnly`
- BREAKING CHANGE: refactor(command): force array in `CommandOptions.preconditions`
> **Note**: `CommandOptions.permissions` has not been added because it's too tied to discord.js, an alternative approach which allows us to go library agnostic will be available later.
=> feat: added auto-preconditions

src/events/command-handler/CoreMessageParser.ts, src/lib/types/Events.ts
Renamed `NonePrefixedMessage` to `NonPrefixedMessage`.
=> fix(NonePrefixedMessage): rename to NonPrefixedMessage

.github/workflows/continuous-delivery.yml
@vladfrangu might want to take a note from reading `npx standard-version --help` :heart:
Also after this PR is merged we can remove the build branch and the branch restriction on it
=> ci: publish next versions to npm

src/lib/utils/strategies/FlagUnorderedStrategy.ts
Allows `flags: true` and `options: true`, also implements a short-circuit system to decrease CPU time when processing flags and options
=> refactor(Flags): add booleans and logic short-circuits

src/lib/structures/Command.ts, src/lib/structures/Precondition.ts, src/lib/types/Enums.ts, src/lib/utils/preconditions/PreconditionContainerArray.ts, src/lib/utils/preconditions/PreconditionContainerSingle.ts, src/lib/utils/preconditions/containers/PermissionsPrecondition.ts, src/preconditions/Cooldown.ts, src/preconditions/Permissions.ts
- Added `Command#parseConstructorPreConditions`.
- Added `Command#parseConstructorPreConditionsRunIn`.
- Added `Command#parseConstructorPreConditionsNsfw`.
- Added `Command#parseConstructorPreConditionsRequiredClientPermissions`.
- Added `Command#parseConstructorPreConditionsCooldown`.
- Added `CommandPreConditions.Permissions`.
- Added `CommandOptions.cooldownScope`.
- Added `CommandOptions.requiredClientPermissions`.
- Added `Preconditions` interface, this strict types all precondition names and contexts.
- Added `PreconditionContainerArray#append`.
- Added `SimplePreconditionSingleResolvableDetails`.
- Fixed cooldown precondition not working when defining alias properties from `Command`.
- :warning: BREAKING CHANGE: Changed `Command#preconditions` to `PreconditionContainerArray`.
- …
=> feat: stricter types for preconditions

src/lib/structures/Listener.ts
With the migration to using `Listener` instead of events, the type for `EventOptions` was missed, and this PR fixes those types.
In addition to this, I scanned the repository for additional mentions of the `EventOptions` and `Event` in general, and did not find anything.
=> refactor(types): rename EventOptions to ListenerOptions

src/lib/structures/Command.ts, src/lib/structures/Precondition.ts, src/preconditions/Cooldown.ts
This way we can filter out users like the bot owner. It is extremely annoying to run into the cooldown when developing a bot.
=> feat(cooldown): add `cooldownFilteredUsers` to exempt users from the cooldown precondition

src/index.ts, src/lib/errors/Identifiers.ts, src/lib/structures/Command.ts, src/lib/structures/Precondition.ts, src/lib/utils/preconditions/containers/ClientPermissionsPrecondition.ts, src/lib/utils/preconditions/containers/UserPermissionsPrecondition.ts, src/preconditions/ClientPermissions.ts, src/preconditions/UserPermissions.ts
Many people have asked, so we deliver
BREAKING CHANGE: `Identifiers.PreconditionPermissions` has been renamed to `Identifiers.PreconditionClientPermissions`
BREAKING CHANGE: UserError identifier `preconditionPermissions` has been renamed to `preconditionClientPermissions`
BREAKING CHANGE: `Permissions` precondition has been renamed to `ClientPermissions`
BREAKING CHANGE: `PermissionsPrecondition` class has been renamed to `ClientPermissionsPrecondition`
=> feat: add UserPermissions precondition

package.json, src/errorListeners/CoreCommandError.ts, src/errorListeners/CoreEventError.ts, src/lib/structures/Command.ts, src/lib/structures/CommandStore.ts, src/lib/structures/Listener.ts, yarn.lock
- **feat** (Command): make `fullCategory` not nullable.
- **refactor** (Command): remove category detection workaround.
- **refactor** (Command): improved logic for `category` getter.
- **refactor** (Command): improved logic for `subCategory` getter.
- **refactor** (Command): improved logic for `parentCategory` getter.
- **refactor** (Command): strict type `toJSON()`.
- **refactor** (Listener): strict type `toJSON()`.
- :warning: **BREAKING CHANGE**: Updated `@sapphire/pieces` to `3.0.0`.
- :warning: **BREAKING CHANGE**: Removed `Command#categories`, use `CommandStore#categories` instead.
=> feat: updated for `pieces` v3

src/listeners/command-handler/CoreMessageParser.ts
After this PR it will also be possible to trigger commands by using `@ManagedRole command`. This is useful because Discord adds a Managed Role with the same name as the Client when adding a bot with permissions, and especially in smaller servers it can happen that you accidentally mention the role instead of the bot.
=> feat: add managed role mention prefix support

src/lib/resolvers/message.ts, yarn.lock
When you hold Shift and hover over a message, then click the "ID" button, you don't actually get the message id, but rather "channelId-messageId".
This commit makes resolveMessage parse this kind of pattern.
=> feat(resolver): make resolveMessage parse channelId-messageId

src/lib/structures/ExtendedArgument.ts
closes #320
Example after change (code taken from v1):
=> feat: deprecate `ExtendedArgument`

src/index.ts, src/preconditions/index.ts
This PR will allow extensions of core preconditions via `CorePreconditions.*`. See also #320.
The code changes themselves are self-explanatory. One change that will affect users is that **`ClientPermissionsCorePrecondition` will now be accessible via `CorePreconditions.ClientPermissions`**.
=> feat(preconditions): export all core preconditions

src/lib/structures/Listener.ts
This is a backport from the fix applied in `origin/trifecta-of-question-marks`
=> fix(Listener): fixed compile issues on TS 4.5

src/preconditions/Cooldown.ts
This will be more accurate when the scope is set to anything other than `USER` because they might've not just used the command. Furthermore, the "just" part is removed, since the cooldown could be 1 hour for all we know, making this a purely factual message 🙂
While you're here, I think it might be worth talking about using `DurationFormatter` from /time-utilities so that things aren't measured in only seconds. However, the drawback would be adding a dependency for a very very small use case in a project that prides itself (or should pride itself) on not having many.
=> refactor: edit cooldown message

src/lib/structures/Command.ts
This was the most logical replacement of names I could think of, but the code itself confused me, so you'll have to tell me if it's actually accurate.
=> style: fix jsdoc for `runIn` option

src/arguments/CoreBoolean.ts, src/lib/resolvers/boolean.ts
Made truths/falses arrays readonly
=> fix: make `BooleanArgument`/`resolveBoolean`'s contexts immutable

src/arguments/CoreEmoji.ts, src/lib/errors/Identifiers.ts, src/lib/parsers/Args.ts, src/lib/resolvers/emoji.ts, src/lib/resolvers/index.ts
With this addition there will be a built-in argument for both global and guild emojis
=> feat: add emoji argument

package.json, src/lib/types/Events.ts, src/listeners/application-commands/chat-input/CoreChatInputCommandAccepted.ts, src/listeners/application-commands/context-menu/CoreContextMenuCommandAccepted.ts, src/optional-listeners/message-command-listeners/CoreMessageCommandAccepted.ts, yarn.lock
New PR after mistakenly autoclosing #356 
---
_Maintainer edit:_
BREAKING CHANGE: The payload for `Events.ChatInputCommandFinish` has been changed from `ChatInputCommandRunPayload` to `ChatInputCommandFinishPayload`
BREAKING CHANGE: The payload for `Events.ContextMenuCommandFinish` has been changed from `ContextMenuCommandRunPayload` to `ContextMenuCommandFinishPayload`
=> feat: add duration to `*Error` and `*Finished` `Message`, `ChatInput` and `ContextMenu` Command events

src/lib/structures/InteractionHandler.ts, src/lib/structures/Precondition.ts
- fix: specify generic for InteractionHandler options
- feat: extract `InteractionHandlerParseResult` from `InteractionHandler` namespace
Namespaced types should be an alternative short-circuit way of accessing those types,
not the only way.
- refactor: change generic in Precondition to use namespaced type
- docs: add tsdoc to `InteractionHandlerOptions.interactionHandlerType`
=> A fix, a feat and a refactor all for Vladdy

src/lib/structures/Command.ts
These namespace members would be great utilities to prevent having to import the registry and interaction every time. (Or doing something like `...[interaction]: Parameters<ChatInputCommand['chatInputRun']>`)
=> feat(command): add Interaction and Registry namespace members

src/lib/structures/Command.ts, tests/Flags.test.ts
French people, and many other languages as a matter of fact, use "« »" as quotation marks too.
=> feat: add "French Quotes" (`«`, `»`) support for quoted args

src/lib/types/Events.ts
I found that *CommandRun and *CommandFinish `command` args used specific `*Command` types for chat input and context menu, but not message. Should I change that?
=> feat(events): add jsdoc description to event enum members

src/index.ts, src/lib/errors/Identifiers.ts, src/lib/structures/Command.ts, src/lib/structures/Precondition.ts, src/preconditions/GuildVoiceOnly.ts
Will allow commands to run only in text in voice channels
=> feat(preconditions): add voice channel only precondition

package.json, src/lib/structures/Command.ts, src/lib/types/Enums.ts, src/lib/utils/application-commands/ApplicationCommandRegistries.ts, src/lib/utils/application-commands/ApplicationCommandRegistry.ts, src/lib/utils/application-commands/computeDifferences.ts, src/lib/utils/application-commands/normalizeInputs.ts, tests/application-commands/computeDifferences.test.ts, yarn.lock
I guess BREAKING CHANGE: RegisterBehavior.Overwrite is now the default behaviorWhenNotEqual, and it now uses object hashing instead of checking each property
=> feat: faster overwrites and string min max length support

src/lib/parsers/Args.ts
- 108f170 feat(args): add `getOptionResult` and `getOptionsResults`
- c58e8d6 feat(args): add `ArgsJSON` type
- c734aa2 fix(args): make `getOption` and `getOptions` return `string | null` again
=> Various `Args` fixes (rebase & merge)

.gitignore, package.json, src/lib/parsers/Args.ts, yarn.lock
This PR removes the leading space when using `Args#rest()` and `Args#restResult()` on arguments after the first one. This was achieved by removing the insertion of the `paramater.leading` value on the first reduction done by `Array#reduce()`, but keeping it for all others (if it isn't kept, the result would have no spaces kindalikethis). Test images and the code used to generate the images are below. I also added `*.tgz` to `.gitingore` as that was generated when I used `yarn pack` to test the changes.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>Test command file used</summary>
````ts
import { ApplyOptions } from '@sapphire/decorators';
import type { Args } from '@sapphire/framework';
import { send } from …
```
=> fix: fixed `args#restResult` including leading space

src/lib/errors/Identifiers.ts, src/lib/utils/preconditions/PreconditionContainerSingle.ts
PreconditionContainerSingle doesn't use result, so when command-specific preconditions that don't implement the corresponding run method are ran in [CorePreChatInputCommandRun.ts](https://github.com/sapphiredev/framework/blob/v3.1.1/src/listeners/application-commands/chat-input/CorePreChatInputCommandRun.ts#L20) the `ChatInputCommandDenied` event isn't emitted (similar issue for `CorePreMessageCommandRun.ts` and `CorePreContextMenuCommandRun.ts`). The error propagates upwards and emits a `ListenerError` event instead.
This uses an approach similar to [PreconditionStore.ts](https://github.com/sapphiredev/framework/blob/v3.1.1/src/lib/structures/PreconditionStore.ts#L32-L51) for global preconditions to fix the issue.
=> fix(precondition): use result for PreconditionContainerSingle

src/lib/structures/CommandStore.ts
`CommandStore#loadAll()` indirectly removes all application command registries. In addition, the Command's `applicationCommandRegistry` being readonly snapshots the command's old registry before it is removed.
As a result, application command registries won't handle api calls after reloading the command store more than once.
This is a hacky patch that gets the job done, so draft pr is only for visibility in hopes of reaching a better solution.
=> fix: reloading the entire command store didn't fire ApplicationCommandRegistries

src/lib/types/Enums.ts, src/lib/utils/application-commands/ApplicationCommandRegistry.ts, src/lib/utils/application-commands/computeDifferences.ts, tests/application-commands/computeDifferences.test.ts
The way getCommandDifferencesFast was built made sense, returning when the first difference was found.
Only issue is that the method it actually used internally, which is the verbose difference one, would still process all differences in the command BEFORE returning, BEFORE getCommandDifferencesFast would see if any difference is present.
Basically it was faster in name only. Now it should actually be faster 🤞
=> fix(computeDifferences): ensure `Overwrite` strategy is actually faster

src/lib/types/Enums.ts, src/lib/utils/application-commands/ApplicationCommandRegistries.ts, src/lib/utils/application-commands/ApplicationCommandRegistry.ts, src/lib/utils/application-commands/registriesLog.ts
Closes #578 
Closes #577 
Closes #579  (Supersedes)
=> feat(ApplicationCommandRegistries): add `RegisterBehavior.BulkOverwrite` which has Sapphire use bulk overwrite for registering Application Commands

src/lib/utils/application-commands/ApplicationCommandRegistry.ts
Critical bug fix reported on https://canary.discord.com/channels/737141877803057244/1062485556954664960
=> fix(ApplicationCommandRegistry): context menu command matching went wrong

src/lib/structures/Command.ts
The old interface exposed options that were not actually supported
by Sapphire, which was misleading. The whole interface could in fact
be removed as it is was an alias for `ApplicationCommandRegistry.RegisterOptions`.
Arguebly a breaking change for TypeScript users, but because the transition to `ApplicationCommandRegistry.RegisterOptions` is a simple find-and-replace we are pushing this out in a minor version.
=> feat: remove `CommandChatInputRegisterShortcut` alias interface, prefer using `ApplicationCommandRegistry.RegisterOptions` instead

src/lib/parsers/Args.ts
This changes the `result.unwrap()` calls to `result.unwrapRaw()` to ensure that the erorr that gets thrown for the following methods:
- `args.pick(...)`
- `args.rest(...)`
- `args.repeat(...)`
- `args.peek(...)` This makes it so that the error that ends up in `messageCommandError` listener will have the proper error type. Furthermore, it can also be handled properly when chaining `.catch()` calls to the `args.X` method.
resolves #528
---
Reproduced the error first with https://github.com/favna/musical-giggle, then confirmed the fix using a debugger with the code from the issue. Also confirmed that it is resolved for `Args.make` by copying the code from https://github.com/favna/repro-sapphire-unwrap-error which was created for a separately reported issue.
=> fix(Args): ensure proper error types are always thrown

src/lib/structures/Command.ts, src/lib/structures/CommandStore.ts, src/lib/utils/application-commands/ApplicationCommandRegistries.ts
This ensures that when `RegisterBehavior.BulkOverwrite` is set, the command does not attempt to register individually which would always cause issues.
resolves #599
=> fix(Command): support `BulkOverwrite` for reloads

src/lib/structures/Argument.ts, src/lib/structures/Command.ts, src/lib/structures/InteractionHandler.ts, src/lib/structures/Listener.ts, src/lib/structures/Precondition.ts
This ensures that people no longed need to write code such as `const commandsStore = this.store as CommandStore` but instead can keep out the typecast.
resolves #382
=> fix: use `declare` for store properties to avoid the need for `as *Store`

src/lib/structures/Command.ts
Back in v2.5.1 the Command class did not have an overwritten `reload` method at all: https://github.com/sapphiredev/framework/blob/v2.5.1/src/lib/structures/Command.ts
This suggests that we didn't actually need to overwrite the reload method when the command to be reloaded doesn't have any chat input or context menu commands. To this end, after this change, whenever a command is exclusively a message command it will also exclusively call `super.reload()`.
=> fix(Command): Do not attempt to execute application command reloading logic when a command does not have any application commands

src/arguments/CoreBoolean.ts, src/arguments/CoreEnum.ts, src/arguments/CoreMessage.ts, src/index.ts, src/lib/types/ArgumentContexts.ts
This will expose the argument context types to the end-users for easier typing.
Version since listed as 4.2.0 because this is to be released alongside #611 which is a https://github.com/sapphiredev/framework/labels/semver%3Aminor
=> refactor: expose argument context types

src/lib/types/Events.ts
Apparently, we forgot to update the `Events` enum to include new (by now quite old) DiscordJS events.
Noticed by: https://discord.com/channels/737141877803057244/1078772436230742108/1078790112118308925
=> fix(events): add missing discordjs events

src/lib/SapphireClient.ts, src/lib/types/Events.ts, src/lib/utils/application-commands/ApplicationCommandRegistries.ts, src/listeners/CoreReady.ts, src/optional-listeners/application-command-registries-listeners/CoreApplicationCommandRegistriesInitialising.ts, src/optional-listeners/application-command-registries-listeners/CoreApplicationCommandRegistriesRegistered.ts
ref: [on ready message - forum post](https://discord.com/channels/737141877803057244/1095353945150468166)
---
This PR addresses a few things:
1. It makes the 2 logs for registering application commands optional by setting the new client option `loadApplicationCommandRegistriesStatusListeners`
2. `Events.ApplicationCommandRegistriesRegistered` can now accept an (optional) `timeTaken` parameter
3. The message `ApplicationCommandRegistries: Initializing...` has been moved from `CoreReady` to `handleRegistryAPICalls` and is emitted to the new event `Events.ApplicationCommandRegistriesInitialising`
4. A core event for `Events.ApplicationCommandRegistriesRegistered` was added that logs the `ApplicationCommandRegistries: Took ${diff.toLocaleString()}ms to initialize.)` message
=> feat: make the Application Command Registries status listeners optional

src/lib/parsers/Args.ts
`ThreadChannel#type` is conflicting with `{ type: ...; parent: ... }` so this pr fixes it.
=> fix(ArgType): update `type` for guild*ThreadChannel

src/index.ts, src/lib/errors/Identifiers.ts, src/lib/structures/Command.ts, src/lib/structures/Precondition.ts, src/preconditions/DMOnly.ts, src/preconditions/GuildNewsOnly.ts, src/preconditions/GuildNewsThreadOnly.ts, src/preconditions/GuildOnly.ts, src/preconditions/GuildPrivateThreadOnly.ts, src/preconditions/GuildPublicThreadOnly.ts, src/preconditions/GuildTextOnly.ts, src/preconditions/GuildThreadOnly.ts, src/preconditions/GuildVoiceOnly.ts, src/preconditions/NSFW.ts, src/preconditions/RunIn.ts
Fixes the issue in thread [`#Eventho runIn has values Guildtext and dm, if run in guild text, error message is shown`](https://discord.com/channels/737141877803057244/1073022367070162955).
I deprecated the following preconditions:
- `DMOnly`
- `GuildNewsOnly`
- `GuildNewsThreadOnly`
- `GuildOnly`
- `GuildPrivateThreadOnly`
- `GuildPublicThreadOnly`
- `GuildTextOnly`
- `GuildThreadOnly`
- `GuildVoiceOnly`
The reason why they were so many different preconditions in the first place, was because:
- Preconditions were added manually, context was bothersome to include **(pre-v2)**.
- Preconditions did very fast synchronous checks **(pre-v3)**.
- It's encouraged to use interactions instead, which would use `await this.fetchChannelFromInteraction(interaction)` for every single precondition. …
=> refactor(preconditions): add `RunIn`, deprecate everything else

src/index.ts, src/lib/parsers/Args.ts, src/lib/structures/Argument.ts, src/lib/structures/Command.ts, src/lib/structures/Precondition.ts, src/lib/structures/PreconditionStore.ts, src/lib/types/CommandTypes.ts, src/lib/types/Enums.ts, src/lib/types/Events.ts, src/lib/utils/preconditions/PreconditionContainerArray.ts, src/lib/utils/preconditions/PreconditionContainerSingle.ts, src/lib/utils/preconditions/conditions/IPreconditionCondition.ts, src/listeners/application-commands/CorePossibleAutocompleteInteraction.ts, src/listeners/application-commands/chat-input/CorePossibleChatInputCommand.ts, src/listeners/application-commands/context-menu/CorePossibleContextMenuCommand.ts, src/optional-listeners/message-command-listeners/CoreMessageCommandTyping.ts, src/optional-listeners/message-command-listeners/CorePrefixedMessage.ts, src/preconditions/RunIn.ts
This way the `Command` file is much shorter and easier to navigate
=> refactor: move command types to its own file

src/index.ts, src/lib/precondition-resolvers/clientPermissions.ts, src/lib/precondition-resolvers/cooldown.ts, src/lib/precondition-resolvers/index.ts, src/lib/precondition-resolvers/nsfw.ts, src/lib/precondition-resolvers/runIn.ts, src/lib/precondition-resolvers/userPermissions.ts, src/lib/structures/Command.ts, tests/precondition-resolvers/clientPermissions.test.ts, tests/precondition-resolvers/cooldown.test.ts, tests/precondition-resolvers/nsfw.test.ts, tests/precondition-resolvers/runIn.test.ts, tests/precondition-resolvers/userPermissions.test.ts, tests/resolvers/boolean.test.ts, tests/resolvers/date.test.ts, tests/resolvers/emoji.test.ts, tests/resolvers/enum.test.ts, tests/resolvers/float.test.ts, tests/resolvers/hyperlink.test.ts, tests/resolvers/integer.test.ts, tests/resolvers/number.test.ts, tests/resolvers/string.test.ts
This gives https://github.com/sapphiredev/plugins/pull/491 a better solution without as much code duplication. The methods `parseConstructorPreConditionsNsfw`, `parseConstructorPreConditionsRunIn`, `parseConstructorPreConditionsRequiredClientPermissions`, `parseConstructorPreConditionsRequiredUserPermissions`, and `parseConstructorPreConditionsCooldown` in the `Command` class are kept because otherwise, this would be a breaking change. I am still unsure if we want to deprecate those methods and remove them in a future major, then call the resolvers directly from `parseConstructorPreConditions` or not.
=> refactor: move preconditions resolvers to dedicated files

src/lib/utils/application-commands/ApplicationCommandRegistry.ts, src/lib/utils/application-commands/compute-differences/_shared.ts, src/lib/utils/application-commands/compute-differences/default_member_permissions.ts, src/lib/utils/application-commands/compute-differences/description.ts, src/lib/utils/application-commands/compute-differences/dm_permission.ts, src/lib/utils/application-commands/compute-differences/localizations.ts, src/lib/utils/application-commands/compute-differences/name.ts, src/lib/utils/application-commands/compute-differences/option.ts, src/lib/utils/application-commands/compute-differences/option/autocomplete.ts, src/lib/utils/application-commands/compute-differences/option/minMaxLength.ts, src/lib/utils/application-commands/compute-differences/option/minMaxValue.ts, src/lib/utils/application-commands/compute-differences/option/required.ts, src/lib/utils/application-commands/compute-differences/option/type.ts, src/lib/utils/application-commands/compute-differences/options.ts, src/lib/utils/application-commands/computeDifferences.ts, src/lib/utils/application-commands/normalizeInputs.ts
Just a cleanup and fixing some missed bugs 
Also adds in checks for `nsfw` command updating
=> fix(computeDifference): correctly check for extra properties and split up compute difference

package.json, tsup.config.ts, yarn.lock
The files output in `dist/cjs` we're still trying to import the `.js` extension despite tsup only building `.cjs` files. This PR adds an esbuild plugin to the tsup config to convert the import extentions.
=> fix: convert .js imports to .cjs

package.json
This solves old plugins importing the CJS version of the framework, causing sapphire's internal pieces to get double loaded (and cause errors)
=> fix: point ESM entrypoint to CJS build

package.json
BREAKING CHANGE: This ensures that Framework will properly load the files from the dist/esm folder. This is BREAKING to ALL plugins that are not equally updated to load ESM specific files because they will otherwise load the CJS files of @sapphire/framework and every piece will load twice. DO NOT use this version without also updating your plugins! Sapphire plugins have been released alongside this version, third-party plugins will need to be updated by their respective authors!!
If you're curious btw, yes this long breaking change will show up properly in the changelog:
```md
- Make ESM properly load ESM endpoint and not masquerade as ESM ([f900c2a](https://github.com/sapphiredev/framework/commit/f900c2abb54d1e9db3687d6ec0964d4629c5f31f))
- 💥 **BREAKING CHANGE:** This ensures that …
```
=> feat!: make ESM properly load ESM endpoint and not masquerade as ESM

src/lib/utils/application-commands/ApplicationCommandRegistries.ts, src/lib/utils/application-commands/ApplicationCommandRegistry.ts
Doesn't break anything funnily enough but its technically wrong
=> fix(ApplicationCommandRegistries): add the right ids in the right place

src/index.ts, src/lib/utils/application-commands/ApplicationCommandRegistries.ts
With Skyra we noticed random time outs, it would be nice if we can retry the request before the error is thrown. This adds that capability. By default only 1 retry is performed, which means no retries. This is to ensure this is a non-breaking change.
=> feat: add option to retry bulk overwrites

src/lib/structures/Command.ts
=> feat(command): add rawName property

src/lib/types/CommandTypes.ts
This pull request fixes a "typo" in the documentation of the `fullCategory` command option example. The author of the example presumably forgot to change the file name in the path provided in the example, so I went ahead and changed it so two different examples are shown with no confusion.
=> docs: fix typo in CommandTypes.ts

src/preconditions/RunIn.ts
This fixes the `RunIn` precondition that shows `message` command for chat input and context menu interactions when throwing error
=> fix(RunIn): show the correct command type when throwing error

src/preconditions/ClientPermissions.ts
`interaction.channel` will always be null when used with user-installable and since `ClientPermissions` always fetch the invoked interaction channel, it will throw an error causing "The application did not respond"
https://github.com/sapphiredev/framework/blob/7ae8c5bded0237bb5862d244e723a121464bb5cc/src/lib/structures/Precondition.ts#L51-L58
=> fix(ClientPermissions): check app permissions when used with user apps

package.json, yarn.lock
Absorbing https://github.com/sapphiredev/pieces/pull/476
=> chore: update pieces to latest

src/preconditions/ClientPermissions.ts
In a likely regression of: https://github.com/sapphiredev/framework/pull/616 setting `requiredClientPermissions` in commands is resulting in consistent fallback messages of:
> I was unable to resolve my permissions in the chat input command invocation channel.
By restoring the fix from https://github.com/sapphiredev/framework/pull/616 client permissions no longer error for our application.
🧪Tested on: Node 22, Discord.js: 14.18.0, cjs distribution
=> fix(ClientPermissions): resolve client permissions for older applications
